import { DateTime } from "luxon";

/**
 * Generic holder for Discord Events
 */
export interface DiscordEvent {

    id: string;                                                 // Autogenerated UUID for reference
    
    type: string;                                               // Discord Event Type (See Eris docs or README)*

    timestamp: DateTime;                                        // Created At Timestamp*
 
    targetGuildId?: string;                                     // Guild interacted with (if applicable)

    targetChannelId?: string;                                   // Channel interacted with (if applicable) 

    targetMessageId?: string;                                   // Any messages interacted with (if applicable)

    sourceEntity?: { type: 'User' | 'Member', id: string };     // User or Member that generated the event (if applicable)*

    targetEntity?: { type: 'User' | 'Member', id: string };     // User or Member that the generated event was targeting

    metadata: any;

}

